/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/_shop'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as ShopIndexRouteImport } from './routes/_shop.index'
import { Route as ShopProductsRouteImport } from './routes/_shop.products'
import { Route as ShopOrdersRouteImport } from './routes/_shop.orders'
import { Route as ShopLoginRouteImport } from './routes/_shop.login'
import { Route as ShopFavoritesRouteImport } from './routes/_shop.favorites'
import { Route as ShopCheckoutRouteImport } from './routes/_shop.checkout'
import { Route as ShopCartRouteImport } from './routes/_shop.cart'
import { Route as ShopAccountRouteImport } from './routes/_shop.account'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin.index'
import { Route as ShopProductsIdRouteImport } from './routes/_shop.products.$id'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin.admin.users'
import { Route as AdminAdminTreasuryRouteImport } from './routes/_admin.admin.treasury'
import { Route as AdminAdminSalesRouteImport } from './routes/_admin.admin.sales'
import { Route as AdminAdminReportsRouteImport } from './routes/_admin.admin.reports'
import { Route as AdminAdminPurchasesRouteImport } from './routes/_admin.admin.purchases'
import { Route as AdminAdminPromotionsRouteImport } from './routes/_admin.admin.promotions'
import { Route as AdminAdminProductsRouteImport } from './routes/_admin.admin.products'
import { Route as AdminAdminOrdersRouteImport } from './routes/_admin.admin.orders'
import { Route as AdminAdminMessagesRouteImport } from './routes/_admin.admin.messages'
import { Route as AdminAdminInventoryRouteImport } from './routes/_admin.admin.inventory'
import { Route as AdminAdminExpensesRouteImport } from './routes/_admin.admin.expenses'
import { Route as AdminAdminExpenseCategoriesRouteImport } from './routes/_admin.admin.expense-categories'
import { Route as AdminAdminDamagedRouteImport } from './routes/_admin.admin.damaged'
import { Route as AdminAdminCouponsRouteImport } from './routes/_admin.admin.coupons'
import { Route as AdminAdminCategoriesRouteImport } from './routes/_admin.admin.categories'
import { Route as AdminAdminBannersRouteImport } from './routes/_admin.admin.banners'
import { Route as AdminAdminAdsRouteImport } from './routes/_admin.admin.ads'
import { Route as AdminAdminSuppliersIndexRouteImport } from './routes/_admin.admin.suppliers.index'
import { Route as AdminAdminCustomersIndexRouteImport } from './routes/_admin.admin.customers.index'
import { Route as AdminAdminSuppliersIdRouteImport } from './routes/_admin.admin.suppliers.$id'
import { Route as AdminAdminCustomersPhoneRouteImport } from './routes/_admin.admin.customers.$phone'

const ShopRoute = ShopRouteImport.update({
  id: '/_shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProductsRoute = ShopProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => ShopRoute,
} as any)
const ShopOrdersRoute = ShopOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ShopRoute,
} as any)
const ShopLoginRoute = ShopLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ShopRoute,
} as any)
const ShopFavoritesRoute = ShopFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCheckoutRoute = ShopCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCartRoute = ShopCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ShopRoute,
} as any)
const ShopAccountRoute = ShopAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShopRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const ShopProductsIdRoute = ShopProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShopProductsRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminTreasuryRoute = AdminAdminTreasuryRouteImport.update({
  id: '/admin/treasury',
  path: '/admin/treasury',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSalesRoute = AdminAdminSalesRouteImport.update({
  id: '/admin/sales',
  path: '/admin/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPurchasesRoute = AdminAdminPurchasesRouteImport.update({
  id: '/admin/purchases',
  path: '/admin/purchases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPromotionsRoute = AdminAdminPromotionsRouteImport.update({
  id: '/admin/promotions',
  path: '/admin/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminProductsRoute = AdminAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminMessagesRoute = AdminAdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminInventoryRoute = AdminAdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminExpensesRoute = AdminAdminExpensesRouteImport.update({
  id: '/admin/expenses',
  path: '/admin/expenses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminExpenseCategoriesRoute =
  AdminAdminExpenseCategoriesRouteImport.update({
    id: '/admin/expense-categories',
    path: '/admin/expense-categories',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminDamagedRoute = AdminAdminDamagedRouteImport.update({
  id: '/admin/damaged',
  path: '/admin/damaged',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCouponsRoute = AdminAdminCouponsRouteImport.update({
  id: '/admin/coupons',
  path: '/admin/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCategoriesRoute = AdminAdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBannersRoute = AdminAdminBannersRouteImport.update({
  id: '/admin/banners',
  path: '/admin/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAdsRoute = AdminAdminAdsRouteImport.update({
  id: '/admin/ads',
  path: '/admin/ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSuppliersIndexRoute =
  AdminAdminSuppliersIndexRouteImport.update({
    id: '/admin/suppliers/',
    path: '/admin/suppliers/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminCustomersIndexRoute =
  AdminAdminCustomersIndexRouteImport.update({
    id: '/admin/customers/',
    path: '/admin/customers/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminSuppliersIdRoute = AdminAdminSuppliersIdRouteImport.update({
  id: '/admin/suppliers/$id',
  path: '/admin/suppliers/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCustomersPhoneRoute =
  AdminAdminCustomersPhoneRouteImport.update({
    id: '/admin/customers/$phone',
    path: '/admin/customers/$phone',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShopIndexRoute
  '/account': typeof ShopAccountRoute
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/favorites': typeof ShopFavoritesRoute
  '/login': typeof ShopLoginRoute
  '/orders': typeof ShopOrdersRoute
  '/products': typeof ShopProductsRouteWithChildren
  '/admin/ads': typeof AdminAdminAdsRoute
  '/admin/banners': typeof AdminAdminBannersRoute
  '/admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/coupons': typeof AdminAdminCouponsRoute
  '/admin/damaged': typeof AdminAdminDamagedRoute
  '/admin/expense-categories': typeof AdminAdminExpenseCategoriesRoute
  '/admin/expenses': typeof AdminAdminExpensesRoute
  '/admin/inventory': typeof AdminAdminInventoryRoute
  '/admin/messages': typeof AdminAdminMessagesRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/products': typeof AdminAdminProductsRoute
  '/admin/promotions': typeof AdminAdminPromotionsRoute
  '/admin/purchases': typeof AdminAdminPurchasesRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/sales': typeof AdminAdminSalesRoute
  '/admin/treasury': typeof AdminAdminTreasuryRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/products/$id': typeof ShopProductsIdRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/customers/$phone': typeof AdminAdminCustomersPhoneRoute
  '/admin/suppliers/$id': typeof AdminAdminSuppliersIdRoute
  '/admin/customers/': typeof AdminAdminCustomersIndexRoute
  '/admin/suppliers/': typeof AdminAdminSuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ShopIndexRoute
  '/account': typeof ShopAccountRoute
  '/cart': typeof ShopCartRoute
  '/checkout': typeof ShopCheckoutRoute
  '/favorites': typeof ShopFavoritesRoute
  '/login': typeof ShopLoginRoute
  '/orders': typeof ShopOrdersRoute
  '/products': typeof ShopProductsRouteWithChildren
  '/admin/ads': typeof AdminAdminAdsRoute
  '/admin/banners': typeof AdminAdminBannersRoute
  '/admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/coupons': typeof AdminAdminCouponsRoute
  '/admin/damaged': typeof AdminAdminDamagedRoute
  '/admin/expense-categories': typeof AdminAdminExpenseCategoriesRoute
  '/admin/expenses': typeof AdminAdminExpensesRoute
  '/admin/inventory': typeof AdminAdminInventoryRoute
  '/admin/messages': typeof AdminAdminMessagesRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/products': typeof AdminAdminProductsRoute
  '/admin/promotions': typeof AdminAdminPromotionsRoute
  '/admin/purchases': typeof AdminAdminPurchasesRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/admin/sales': typeof AdminAdminSalesRoute
  '/admin/treasury': typeof AdminAdminTreasuryRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/products/$id': typeof ShopProductsIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/customers/$phone': typeof AdminAdminCustomersPhoneRoute
  '/admin/suppliers/$id': typeof AdminAdminSuppliersIdRoute
  '/admin/customers': typeof AdminAdminCustomersIndexRoute
  '/admin/suppliers': typeof AdminAdminSuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_shop': typeof ShopRouteWithChildren
  '/_shop/account': typeof ShopAccountRoute
  '/_shop/cart': typeof ShopCartRoute
  '/_shop/checkout': typeof ShopCheckoutRoute
  '/_shop/favorites': typeof ShopFavoritesRoute
  '/_shop/login': typeof ShopLoginRoute
  '/_shop/orders': typeof ShopOrdersRoute
  '/_shop/products': typeof ShopProductsRouteWithChildren
  '/_shop/': typeof ShopIndexRoute
  '/_admin/admin/ads': typeof AdminAdminAdsRoute
  '/_admin/admin/banners': typeof AdminAdminBannersRoute
  '/_admin/admin/categories': typeof AdminAdminCategoriesRoute
  '/_admin/admin/coupons': typeof AdminAdminCouponsRoute
  '/_admin/admin/damaged': typeof AdminAdminDamagedRoute
  '/_admin/admin/expense-categories': typeof AdminAdminExpenseCategoriesRoute
  '/_admin/admin/expenses': typeof AdminAdminExpensesRoute
  '/_admin/admin/inventory': typeof AdminAdminInventoryRoute
  '/_admin/admin/messages': typeof AdminAdminMessagesRoute
  '/_admin/admin/orders': typeof AdminAdminOrdersRoute
  '/_admin/admin/products': typeof AdminAdminProductsRoute
  '/_admin/admin/promotions': typeof AdminAdminPromotionsRoute
  '/_admin/admin/purchases': typeof AdminAdminPurchasesRoute
  '/_admin/admin/reports': typeof AdminAdminReportsRoute
  '/_admin/admin/sales': typeof AdminAdminSalesRoute
  '/_admin/admin/treasury': typeof AdminAdminTreasuryRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_shop/products/$id': typeof ShopProductsIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/customers/$phone': typeof AdminAdminCustomersPhoneRoute
  '/_admin/admin/suppliers/$id': typeof AdminAdminSuppliersIdRoute
  '/_admin/admin/customers/': typeof AdminAdminCustomersIndexRoute
  '/_admin/admin/suppliers/': typeof AdminAdminSuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/orders'
    | '/products'
    | '/admin/ads'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/damaged'
    | '/admin/expense-categories'
    | '/admin/expenses'
    | '/admin/inventory'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/purchases'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/treasury'
    | '/admin/users'
    | '/products/$id'
    | '/admin/'
    | '/admin/customers/$phone'
    | '/admin/suppliers/$id'
    | '/admin/customers/'
    | '/admin/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/orders'
    | '/products'
    | '/admin/ads'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/damaged'
    | '/admin/expense-categories'
    | '/admin/expenses'
    | '/admin/inventory'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/purchases'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/treasury'
    | '/admin/users'
    | '/products/$id'
    | '/admin'
    | '/admin/customers/$phone'
    | '/admin/suppliers/$id'
    | '/admin/customers'
    | '/admin/suppliers'
  id:
    | '__root__'
    | '/_admin'
    | '/_shop'
    | '/_shop/account'
    | '/_shop/cart'
    | '/_shop/checkout'
    | '/_shop/favorites'
    | '/_shop/login'
    | '/_shop/orders'
    | '/_shop/products'
    | '/_shop/'
    | '/_admin/admin/ads'
    | '/_admin/admin/banners'
    | '/_admin/admin/categories'
    | '/_admin/admin/coupons'
    | '/_admin/admin/damaged'
    | '/_admin/admin/expense-categories'
    | '/_admin/admin/expenses'
    | '/_admin/admin/inventory'
    | '/_admin/admin/messages'
    | '/_admin/admin/orders'
    | '/_admin/admin/products'
    | '/_admin/admin/promotions'
    | '/_admin/admin/purchases'
    | '/_admin/admin/reports'
    | '/_admin/admin/sales'
    | '/_admin/admin/treasury'
    | '/_admin/admin/users'
    | '/_shop/products/$id'
    | '/_admin/admin/'
    | '/_admin/admin/customers/$phone'
    | '/_admin/admin/suppliers/$id'
    | '/_admin/admin/customers/'
    | '/_admin/admin/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shop': {
      id: '/_shop'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shop/': {
      id: '/_shop/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/products': {
      id: '/_shop/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ShopProductsRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/orders': {
      id: '/_shop/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof ShopOrdersRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/login': {
      id: '/_shop/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof ShopLoginRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/favorites': {
      id: '/_shop/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof ShopFavoritesRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/checkout': {
      id: '/_shop/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof ShopCheckoutRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/cart': {
      id: '/_shop/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof ShopCartRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_shop/account': {
      id: '/_shop/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ShopAccountRouteImport
      parentRoute: typeof ShopRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_shop/products/$id': {
      id: '/_shop/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ShopProductsIdRouteImport
      parentRoute: typeof ShopProductsRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/treasury': {
      id: '/_admin/admin/treasury'
      path: '/admin/treasury'
      fullPath: '/admin/treasury'
      preLoaderRoute: typeof AdminAdminTreasuryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/sales': {
      id: '/_admin/admin/sales'
      path: '/admin/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminAdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/reports': {
      id: '/_admin/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/purchases': {
      id: '/_admin/admin/purchases'
      path: '/admin/purchases'
      fullPath: '/admin/purchases'
      preLoaderRoute: typeof AdminAdminPurchasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/promotions': {
      id: '/_admin/admin/promotions'
      path: '/admin/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminAdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/products': {
      id: '/_admin/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminAdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/orders': {
      id: '/_admin/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/messages': {
      id: '/_admin/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminAdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory': {
      id: '/_admin/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminAdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/expenses': {
      id: '/_admin/admin/expenses'
      path: '/admin/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AdminAdminExpensesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/expense-categories': {
      id: '/_admin/admin/expense-categories'
      path: '/admin/expense-categories'
      fullPath: '/admin/expense-categories'
      preLoaderRoute: typeof AdminAdminExpenseCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/damaged': {
      id: '/_admin/admin/damaged'
      path: '/admin/damaged'
      fullPath: '/admin/damaged'
      preLoaderRoute: typeof AdminAdminDamagedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/coupons': {
      id: '/_admin/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminAdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/categories': {
      id: '/_admin/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminAdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/banners': {
      id: '/_admin/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminAdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/ads': {
      id: '/_admin/admin/ads'
      path: '/admin/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/suppliers/': {
      id: '/_admin/admin/suppliers/'
      path: '/admin/suppliers'
      fullPath: '/admin/suppliers/'
      preLoaderRoute: typeof AdminAdminSuppliersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/customers/': {
      id: '/_admin/admin/customers/'
      path: '/admin/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminAdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/suppliers/$id': {
      id: '/_admin/admin/suppliers/$id'
      path: '/admin/suppliers/$id'
      fullPath: '/admin/suppliers/$id'
      preLoaderRoute: typeof AdminAdminSuppliersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/customers/$phone': {
      id: '/_admin/admin/customers/$phone'
      path: '/admin/customers/$phone'
      fullPath: '/admin/customers/$phone'
      preLoaderRoute: typeof AdminAdminCustomersPhoneRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAdsRoute: typeof AdminAdminAdsRoute
  AdminAdminBannersRoute: typeof AdminAdminBannersRoute
  AdminAdminCategoriesRoute: typeof AdminAdminCategoriesRoute
  AdminAdminCouponsRoute: typeof AdminAdminCouponsRoute
  AdminAdminDamagedRoute: typeof AdminAdminDamagedRoute
  AdminAdminExpenseCategoriesRoute: typeof AdminAdminExpenseCategoriesRoute
  AdminAdminExpensesRoute: typeof AdminAdminExpensesRoute
  AdminAdminInventoryRoute: typeof AdminAdminInventoryRoute
  AdminAdminMessagesRoute: typeof AdminAdminMessagesRoute
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRoute
  AdminAdminProductsRoute: typeof AdminAdminProductsRoute
  AdminAdminPromotionsRoute: typeof AdminAdminPromotionsRoute
  AdminAdminPurchasesRoute: typeof AdminAdminPurchasesRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
  AdminAdminSalesRoute: typeof AdminAdminSalesRoute
  AdminAdminTreasuryRoute: typeof AdminAdminTreasuryRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminCustomersPhoneRoute: typeof AdminAdminCustomersPhoneRoute
  AdminAdminSuppliersIdRoute: typeof AdminAdminSuppliersIdRoute
  AdminAdminCustomersIndexRoute: typeof AdminAdminCustomersIndexRoute
  AdminAdminSuppliersIndexRoute: typeof AdminAdminSuppliersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAdsRoute: AdminAdminAdsRoute,
  AdminAdminBannersRoute: AdminAdminBannersRoute,
  AdminAdminCategoriesRoute: AdminAdminCategoriesRoute,
  AdminAdminCouponsRoute: AdminAdminCouponsRoute,
  AdminAdminDamagedRoute: AdminAdminDamagedRoute,
  AdminAdminExpenseCategoriesRoute: AdminAdminExpenseCategoriesRoute,
  AdminAdminExpensesRoute: AdminAdminExpensesRoute,
  AdminAdminInventoryRoute: AdminAdminInventoryRoute,
  AdminAdminMessagesRoute: AdminAdminMessagesRoute,
  AdminAdminOrdersRoute: AdminAdminOrdersRoute,
  AdminAdminProductsRoute: AdminAdminProductsRoute,
  AdminAdminPromotionsRoute: AdminAdminPromotionsRoute,
  AdminAdminPurchasesRoute: AdminAdminPurchasesRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
  AdminAdminSalesRoute: AdminAdminSalesRoute,
  AdminAdminTreasuryRoute: AdminAdminTreasuryRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminCustomersPhoneRoute: AdminAdminCustomersPhoneRoute,
  AdminAdminSuppliersIdRoute: AdminAdminSuppliersIdRoute,
  AdminAdminCustomersIndexRoute: AdminAdminCustomersIndexRoute,
  AdminAdminSuppliersIndexRoute: AdminAdminSuppliersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ShopProductsRouteChildren {
  ShopProductsIdRoute: typeof ShopProductsIdRoute
}

const ShopProductsRouteChildren: ShopProductsRouteChildren = {
  ShopProductsIdRoute: ShopProductsIdRoute,
}

const ShopProductsRouteWithChildren = ShopProductsRoute._addFileChildren(
  ShopProductsRouteChildren,
)

interface ShopRouteChildren {
  ShopAccountRoute: typeof ShopAccountRoute
  ShopCartRoute: typeof ShopCartRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopFavoritesRoute: typeof ShopFavoritesRoute
  ShopLoginRoute: typeof ShopLoginRoute
  ShopOrdersRoute: typeof ShopOrdersRoute
  ShopProductsRoute: typeof ShopProductsRouteWithChildren
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopAccountRoute: ShopAccountRoute,
  ShopCartRoute: ShopCartRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopFavoritesRoute: ShopFavoritesRoute,
  ShopLoginRoute: ShopLoginRoute,
  ShopOrdersRoute: ShopOrdersRoute,
  ShopProductsRoute: ShopProductsRouteWithChildren,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
